[2023-07-30 17:48:11,527] 	INFO 	20 	id_data.py 	<module>() 	ID Data Started
[2023-07-30 17:48:12,031] 	ERROR 	33 	id_data.py 	<module>() 	Error occurred during ID Data process. Error: Expecting value: line 1 column 1 (char 0)
Traceback (most recent call last):
  File "C:\Users\Admin\Documents\Projects\Retro-Data\env\lib\site-packages\requests\models.py", line 971, in json
    return complexjson.loads(self.text, **kwargs)
  File "C:\Users\Admin\Documents\Projects\Retro-Data\env\lib\json\__init__.py", line 357, in loads
    return _default_decoder.decode(s)
  File "C:\Users\Admin\Documents\Projects\Retro-Data\env\lib\json\decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "C:\Users\Admin\Documents\Projects\Retro-Data\env\lib\json\decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "id_data.py", line 27, in <module>
    data = response.json()["data"]
  File "C:\Users\Admin\Documents\Projects\Retro-Data\env\lib\site-packages\requests\models.py", line 975, in json
    raise RequestsJSONDecodeError(e.msg, e.doc, e.pos)
requests.exceptions.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
[2023-07-30 17:48:53,398] 	INFO 	20 	id_data.py 	<module>() 	ID Data Started
[2023-07-30 17:48:53,919] 	INFO 	31 	id_data.py 	<module>() 	ID Data Ended
[2023-07-30 13:55:06,364] 	INFO 	20 	id_data.py 	<module>() 	ID Data Started
[2023-07-30 13:55:06,819] 	INFO 	31 	id_data.py 	<module>() 	ID Data Ended
[2023-07-30 13:55:07,660] 	INFO 	79 	day_data.py 	<module>() 	Day Data Fusion Started
[2023-07-30 13:55:09,168] 	ERROR 	128 	day_data.py 	<module>() 	Error occurred during Day Data Fusion process. Error: Master
Traceback (most recent call last):
  File "/opt/hostedtoolcache/Python/3.8.17/x64/lib/python3.8/site-packages/gspread/spreadsheet.py", line 335, in worksheet
    item = finditem(
  File "/opt/hostedtoolcache/Python/3.8.17/x64/lib/python3.8/site-packages/gspread/utils.py", line 133, in finditem
    return next(item for item in seq if func(item))
StopIteration

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "day_data.py", line 116, in <module>
    worksheet1 = gs.worksheet("Master")
  File "/opt/hostedtoolcache/Python/3.8.17/x64/lib/python3.8/site-packages/gspread/spreadsheet.py", line 341, in worksheet
    raise WorksheetNotFound(title)
gspread.exceptions.WorksheetNotFound: Master
[2023-07-30 13:56:44,941] 	INFO 	20 	id_data.py 	<module>() 	ID Data Started
[2023-07-30 13:56:45,355] 	INFO 	31 	id_data.py 	<module>() 	ID Data Ended
[2023-07-30 13:56:45,864] 	INFO 	79 	day_data.py 	<module>() 	Day Data Fusion Started
[2023-07-30 13:56:48,900] 	INFO 	126 	day_data.py 	<module>() 	Day Data Fusion Ended
[2023-07-30 14:13:19,028] 	INFO 	20 	id_data.py 	<module>() 	ID Data Started
[2023-07-30 14:13:19,626] 	INFO 	31 	id_data.py 	<module>() 	ID Data Ended
[2023-07-30 14:13:20,166] 	INFO 	79 	day_data.py 	<module>() 	Day Data Fusion Started
[2023-07-30 14:13:22,632] 	INFO 	126 	day_data.py 	<module>() 	Day Data Fusion Ended
[2023-07-30 14:15:38,667] 	INFO 	20 	id_data.py 	<module>() 	ID Data Started
[2023-07-30 14:15:39,129] 	INFO 	31 	id_data.py 	<module>() 	ID Data Ended
[2023-07-30 15:15:12,637] 	INFO 	20 	id_data.py 	<module>() 	ID Data Started
[2023-07-30 15:15:12,946] 	INFO 	31 	id_data.py 	<module>() 	ID Data Ended
[2023-07-30 15:15:13,609] 	INFO 	79 	day_data.py 	<module>() 	Day Data Fusion Started
[2023-07-30 15:15:15,793] 	INFO 	126 	day_data.py 	<module>() 	Day Data Fusion Ended
[2023-07-30 15:36:21,936] 	INFO 	123 	pair_data.py 	<module>() 	Pair Data Fusion Started
[2023-07-30 15:36:33,288] 	INFO 	187 	pair_data.py 	<module>() 	Pair Data Fusion Ended
[2023-07-30 15:40:09,862] 	INFO 	20 	id_data.py 	<module>() 	ID Data Started
[2023-07-30 15:40:10,346] 	INFO 	31 	id_data.py 	<module>() 	ID Data Ended
[2023-07-30 15:40:11,138] 	INFO 	79 	day_data.py 	<module>() 	Day Data Fusion Started
[2023-07-30 15:40:31,590] 	INFO 	126 	day_data.py 	<module>() 	Day Data Fusion Ended
[2023-07-30 15:43:39,763] 	INFO 	20 	id_data.py 	<module>() 	ID Data Started
[2023-07-30 15:43:40,439] 	INFO 	31 	id_data.py 	<module>() 	ID Data Ended
[2023-07-30 15:43:41,126] 	INFO 	79 	day_data.py 	<module>() 	Day Data Fusion Started
[2023-07-30 15:43:43,891] 	INFO 	126 	day_data.py 	<module>() 	Day Data Fusion Ended
[2023-07-30 15:43:45,053] 	INFO 	123 	pair_data.py 	<module>() 	Pair Data Fusion Started
[2023-07-30 15:43:56,941] 	INFO 	187 	pair_data.py 	<module>() 	Pair Data Fusion Ended
[2023-07-30 16:19:33,497] 	INFO 	20 	id_data.py 	<module>() 	ID Data Started
[2023-07-30 16:19:33,817] 	INFO 	31 	id_data.py 	<module>() 	ID Data Ended
[2023-07-30 16:19:34,470] 	INFO 	79 	day_data.py 	<module>() 	Day Data Fusion Started
[2023-07-30 16:19:36,651] 	INFO 	126 	day_data.py 	<module>() 	Day Data Fusion Ended
[2023-07-30 16:19:37,994] 	INFO 	123 	pair_data.py 	<module>() 	Pair Data Fusion Started
[2023-07-30 16:19:48,574] 	INFO 	187 	pair_data.py 	<module>() 	Pair Data Fusion Ended
[2023-07-30 16:26:21,243] 	INFO 	123 	pair_data.py 	<module>() 	Pair Data Fusion Started
[2023-07-30 16:26:31,703] 	INFO 	187 	pair_data.py 	<module>() 	Pair Data Fusion Ended
[2023-07-30 16:56:48,805] 	INFO 	123 	pair_data.py 	<module>() 	Pair Data Fusion Started
[2023-07-30 16:56:59,189] 	INFO 	187 	pair_data.py 	<module>() 	Pair Data Fusion Ended
[2023-07-30 17:13:31,078] 	INFO 	20 	id_data.py 	<module>() 	ID Data Started
[2023-07-30 17:13:31,569] 	INFO 	31 	id_data.py 	<module>() 	ID Data Ended
[2023-07-30 17:13:32,282] 	INFO 	79 	day_data.py 	<module>() 	Day Data Fusion Started
[2023-07-30 17:13:34,777] 	INFO 	126 	day_data.py 	<module>() 	Day Data Fusion Ended
[2023-07-30 17:13:36,072] 	INFO 	123 	pair_data.py 	<module>() 	Pair Data Fusion Started
[2023-07-30 17:13:47,611] 	INFO 	187 	pair_data.py 	<module>() 	Pair Data Fusion Ended
[2023-07-30 18:19:11,504] 	INFO 	20 	id_data.py 	<module>() 	ID Data Started
[2023-07-30 18:19:11,828] 	INFO 	31 	id_data.py 	<module>() 	ID Data Ended
[2023-07-30 18:19:12,619] 	INFO 	79 	day_data.py 	<module>() 	Day Data Fusion Started
[2023-07-30 18:19:15,296] 	INFO 	126 	day_data.py 	<module>() 	Day Data Fusion Ended
[2023-07-30 18:19:16,693] 	INFO 	123 	pair_data.py 	<module>() 	Pair Data Fusion Started
[2023-07-30 18:19:28,172] 	INFO 	187 	pair_data.py 	<module>() 	Pair Data Fusion Ended
[2023-07-30 19:12:10,629] 	INFO 	20 	id_data.py 	<module>() 	ID Data Started
[2023-07-30 19:12:11,098] 	INFO 	31 	id_data.py 	<module>() 	ID Data Ended
[2023-07-30 19:12:11,806] 	INFO 	79 	day_data.py 	<module>() 	Day Data Fusion Started
[2023-07-30 19:12:13,928] 	INFO 	126 	day_data.py 	<module>() 	Day Data Fusion Ended
[2023-07-30 19:12:15,233] 	INFO 	123 	pair_data.py 	<module>() 	Pair Data Fusion Started
[2023-07-30 19:12:26,385] 	INFO 	187 	pair_data.py 	<module>() 	Pair Data Fusion Ended
[2023-07-30 20:15:41,189] 	INFO 	20 	id_data.py 	<module>() 	ID Data Started
[2023-07-30 20:15:41,553] 	INFO 	31 	id_data.py 	<module>() 	ID Data Ended
[2023-07-30 20:15:42,121] 	INFO 	79 	day_data.py 	<module>() 	Day Data Fusion Started
[2023-07-30 20:15:44,144] 	INFO 	126 	day_data.py 	<module>() 	Day Data Fusion Ended
[2023-07-30 20:15:45,239] 	INFO 	123 	pair_data.py 	<module>() 	Pair Data Fusion Started
[2023-07-30 20:15:55,875] 	INFO 	187 	pair_data.py 	<module>() 	Pair Data Fusion Ended
